version: 2

sources:
  - name: lego_staging
    database: lego-investments
    schema: lego_staging
    description: "Raw data ingested from Rebrickable and Bricklink Scrapers"
    tables:
      - name: src_prices
        description: "Historical price observation for Lego ets scraped from Bricklink"
        columns: 
          - name: set_id
            tests:
              - not_null
          - name: observed_date
            tests:
              - not_null
      - name: src_sets
        description: "Lego set metadata ingested from Rebrickable API"
        columns:
          - name: set_id
            tests:
              - unique
              - not_null
      - name: src_minifigures
        description: "Unique list of Lego minifigures"
      - name: src_set_minifigures
        description: "Junction table linking sets to minifigures"
